### ISSUE TITLE
UI inconveniences

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-BookStore#168]
1) typing in the username field resets the password
![ef6eea51-9ea7-4013-8704-f39ca9aa6309](https://user-images.githubusercontent.com/4236651/30751387-820b8212-9fb9-11e7-8625-c65937d7e581.gif)

Not sure if on purpose or not, but at the least it is different to 99% of other websites out there and a bit unexpected

2) "Add" button becomes green with just title and authors, but doesn't actually work until I add a link
3) Clicking Add resets only two of three fields

![1a786eb8-0ec3-4248-92e4-52af3ca5c474](https://user-images.githubusercontent.com/4236651/30751756-86e812e0-9fba-11e7-9911-6811bbdb66f5.gif)

4) I can add duplicates, but deleting _any_ deletes _all_.
![b28cc0af-29ac-4a74-9de1-5c0a43e3d741](https://user-images.githubusercontent.com/4236651/30751705-55c82eca-9fba-11e7-8ac8-571c1cd30238.gif)

**Comment by forki** [comment]
happy to take PRs ;-)

**Comment by 0x53A** [comment]
http://fable-suave.azurewebsites.net/ is different than ``build.cmd run``.

1) is worse.

![a16c7f25-b0e4-4ba0-b8c9-1af5551f6910](https://user-images.githubusercontent.com/4236651/30762390-21e639a8-9fe2-11e7-9a71-8840acb87bb6.gif)



2) 3) are already fixed

4) I can still add duplicates, but removing only removes one. Still think adding duplicates should be prohibited.

Also, the input fields no longer become green, that was kind of neat. Purpose or accident?

-------

Would be cool if CI would push to http://fable-suave.azurewebsites.net/ automatically ;-)

**Comment by forki** [comment]
Yes that would be cool. But at the time of writing the build script this
wasn't possible with azure. I ended up with a mailing thread where
basically half of Redmond was involved.
But it's time for a new trial. So please open new issue for it.

Am 22.09.2017 22:05 schrieb "Lukas Rieger" <notifications@github.com>:

**Comment by forki** [comment]
everything can now easily be pushed to docker hub and azure websites.
http://fable-suave.azurewebsites.net/#home is up-to-date
