### ISSUE TITLE
Activate CI

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-BookStore#175]
After moving the fable suave scaffold we lost CI.

@isaacabraham can you please activate an AppVeyor and travis account for this org?

**Comment by Krzysztof-Cieslak** [comment]
Since we're using docker anyway, we could try CircleCI to do tests on exactly same environment as in production https://circleci.com

**Comment by isaacabraham** [comment]
Sounds like a good idea :-)

**Comment by forki** [comment]
@Krzysztof-Cieslak go for it! and contact me on slack if you need something
