### ISSUE TITLE
Update gifs to use hot reload

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-BookStore#187]

**Comment by forki** [comment]
how about this one?

![fasthmr](https://user-images.githubusercontent.com/57396/31067904-bec572e6-a755-11e7-967d-c169724006f2.gif)

**Comment by vasily-kirichenko** [comment]
I think the part where everything is starting up should be removed - it takes a long time and it's completely unrelated to HMR.

**Comment by forki** [comment]
But the image is at the beginning of the readme - exactly at the place that talks about "build.run"

**Comment by vasily-kirichenko** [comment]
OK, I see.
