### ISSUE TITLE
Bundle shim.min.js and fetch.js with webpack

### ISSUE THREAD

**Issue by kerams** [SAFE-Stack/SAFE-BookStore#189]
Is it necessary to keep the 2 files in the project rather than adding them to `packages.json`?

See `index.html`
```html
<script src="js/shim.min.js"></script>
<script src="js/fetch.js"></script>
```

**Comment by forki** [comment]
@MangelMaxime @alfonsogarciacaro how can we bundle it? and do we want to?

**Comment by kerams** [comment]
Fetch https://www.npmjs.com/package/whatwg-fetch
Shim https://www.npmjs.com/package/core-js

I'm not sure whether Webpack would boil the whole core-js file down to the minified version at https://cdnjs.com/libraries/core-js/2.4.1

**Comment by kerams** [comment]
Incidentally, `yarn.lock` already contains both of these, so we could just remove them?

**Comment by MangelMaxime** [comment]
@forki For fetch I think doing: `JsInterop.importAll "whatwg-fetch"` works.

We have it in [this sample](https://github.com/fable-elmish/sample-react-navigation/blob/master/src/app.fs#L16)

**Comment by forki** [comment]
ok what about the other one?

**Comment by MangelMaxime** [comment]
For `shim.min.js`, I am not sure but I think we can just remove it completely.

We are using babel [here](https://github.com/SAFE-Stack/SAFE-BookStore/blob/master/src/Client/webpack.config.js#L9-L12) which should already include everything needed to support ES2015.

Also, we should now use [babel-env](https://babeljs.io/docs/plugins/preset-env/) from now as presets has been deprecated.

**Comment by forki** [comment]
can you send the PR for babel-env?
I will remove the shim

**Comment by forki** [comment]
@MangelMaxime https://github.com/SAFE-Stack/SAFE-BookStore/pull/192 looks like removing it breaks the build

**Comment by MangelMaxime** [comment]
@forki Sure, I will do

**Comment by MangelMaxime** [comment]
@forki Hum, I will take a look about the shim stuff. Because, I use the same stack as this project without shim and the UITests were working last time I run them.

**Comment by MangelMaxime** [comment]
@forki I can't run the UITest suites on my computer because it's complain about missing references for `.NETFramework,Version=v4.6.1` but when I try to install .Net4.6.1 it's say that I have it or newer... All fun...

I found [this documentation](https://babeljs.io/docs/usage/polyfill/#usage-in-node-browserify-webpack). So perhaps we should do `JsInterop.importSideEffects "babel-polyfill"`

From my research it should be equivalent to what `shim.js` do.

If you can test it would be cool, otherwise I will take a look at it this evening from my Linux laptop.

**Comment by forki** [comment]
Just left office, can you please just send as pr? We can ask  CI ;-)

Am 02.10.2017 16:45 schrieb "Maxime Mangel" <notifications@github.com>:
