### ISSUE TITLE
Freya back-end version

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-BookStore#199]
Linked to #196, it would be really great to have an equivalent fork of this repository that used Freya.

**Comment by isaacabraham** [comment]
Who should we contact on the Freya team about this? I would sooner have someone from the team or who is experienced in it give a great example of how it can work.

**Comment by isaacabraham** [comment]
@panesofglass @kolektiv what are your thoughts on this?

**Comment by panesofglass** [comment]
@neoeinstein has been the most active with Freya of late. I would love to see such a sample.

**Comment by nojaf** [comment]
Started working on a port to [freya](https://github.com/nojaf/SAFE-BookStore/tree/freya).
No freya expert by any means.
Any help, feedback or suggestions are welcome.

**Comment by nojaf** [comment]
Ok, got everything working. The code still needs a lot of cleaning up.

 Could somebody perhaps create a freya branch so that I can create a [WIP] pull request?

**Comment by nojaf** [comment]
@forki @alfonsogarciacaro should I do the PR against the master branch?

**Comment by alfonsogarciacaro** [comment]
Hi @nojaf! Sorry, I wasn't watching the repo and didn't get the previous notification. I created the `freya` branch :+1: We can add a note to the README later in master so people are aware the branch exists :)
