### ISSUE TITLE
Refactor Page and SubModel types

### ISSUE THREAD

**Issue by kerams** [SAFE-Stack/SAFE-BookStore#209]
`App.Model` and the related types are currently defined as follows:
```fsharp
type Page =
    | Home
    | Login
    | WishList

type SubModel =
    | NoSubModel
    | LoginModel of Login.Model
    | WishListModel of WishList.Model

type Model =
    { Page : Page
      Menu : Menu.Model
      SubModel : SubModel }
```
Because of this, it is theoretically possible that an instance of `Model` consists of `Page.Login` and `SubModel.NoSubModel`. As a result, `App.viewPage` needs to contain match cases with no value, such as:
```fsharp
| Page.Login ->
    match model.SubModel with
    | LoginModel m ->
        [ div [ ] [ Login.view m dispatch ]]
    | _ -> [ ]
```

In keeping with the approach of making illegal states unrepresentable, I propose to conflate `Page` and `SubModel` into something like:
```fsharp
type Page =
    | Home
    | Login of Login.Model
    | WishList of WishList.Model
```
This would require some juggling because of dependencies across modules.

**Comment by forki** [comment]
I think it's worth a try

Am 09.10.2017 20:02 schrieb "kerams" <notifications@github.com>:

**Comment by kerams** [comment]
This is proving to be very tricky, because `Page` is used by functions dealing with URL changes, which would not really be possible if the DU cases carried models.

About the only solution I could think of is simply removing `Page` from `App.Model` and using `SubModel` to indicate what page we're on. This way no illegal state can be represented. Not really sure if it's a good change though. Thoughts?

**Comment by forki** [comment]
yes we don't need the page DU. If you can make the url parser work with the submodel then Pages.fs can go

**Comment by kerams** [comment]
>If you can make the url parser work with the submodel then Pages.fs can go
Unfortunately, I don't see how that would be possible, consider a line from `Menu.fs`:
```
yield viewLink Page.WishList "Wishlist"
```
If `viewLink` accepted `SubModel`, you would have to pass along `WishList.Model`, don't and can't have access to in `Menu`. Similarly, you'd have to start creating models in `pageParser`.

What I proposed is really just removing `Page` from `App.Model`, it would not cease to exist altogether.

**Comment by kerams** [comment]
@forki Something like https://github.com/kerams/SAFE-BookStore/tree/experiment

**Comment by forki** [comment]
Please send pr so that we can see diff

Am 13.10.2017 18:49 schrieb "kerams" <notifications@github.com>:
