### ISSUE TITLE
Deployment story to Azure App Service

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-BookStore#215]
### Description

An alternative (and probably more well-known) mechanism to deploy .NET applications on the Azure App Service is through Kudu without the dependency on Docker and ACS. There should be a documented process for this for the bookstore app.

**Comment by forki** [comment]
I seriously question that kudo is more known than docker ;-)
But yes let's do it

Am 11.10.2017 18:29 schrieb "Isaac Abraham" <notifications@github.com>:

**Comment by isaacabraham** [comment]
You know what I mean - people that are deploying .NET applications today in Azure are (I would strongly imagine) using App Service bare, not with ACS.

**Comment by martinbryant** [comment]
#432 is for upgrading the application to SAFE v5
