### ISSUE TITLE
It does not compile

### ISSUE THREAD

**Issue by vasily-kirichenko** [SAFE-Stack/SAFE-BookStore#242]
> ERROR in C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/navigation.fs
Module not found: Error: Can't resolve '../../../fable.core/1.2.4/fable-core/Option' in 'C:\Users\kirichenko\.nuget\packages\fable.elmish.browser\1.0.0\fable'
 @ C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/navigation.fs 8:0-71
 @ ./App.fs
 @ ./Client.fsproj

ERROR in C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/parser.fs
Module not found: Error: Can't resolve '../../../fable.core/1.2.4/fable-core/Option' in 'C:\Users\kirichenko\.nuget\packages\fable.elmish.browser\1.0.0\fable'
 @ C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/parser.fs 13:0-79
 @ ./Pages.fs
 @ ./App.fs
 @ ./Client.fsproj

ERROR in C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/prelude.fs
Module not found: Error: Can't resolve '../../../fable.core/1.2.4/fable-core/Option' in 'C:\Users\kirichenko\.nuget\packages\fable.elmish.browser\1.0.0\fable'
 @ C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/prelude.fs 1:0-77
 @ C:/Users/kirichenko/.nuget/packages/fable.elmish.browser/1.0.0/fable/parser.fs
 @ ./Pages.fs
 @ ./App.fs
 @ ./Client.fsproj

ERROR in C:/Users/kirichenko/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs
Module not found: Error: Can't resolve '../../../fable.core/1.2.4/fable-core/Option' in 'C:\Users\kirichenko\.nuget\packages\fable.elmish.react\1.0.0\fable'
 @ C:/Users/kirichenko/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs 1:0-71
 @ ./App.fs
 @ ./Client.fsproj

ERROR in ./App.fs
Module not found: Error: Can't resolve 'C:/Users/kirichenko/.nuget/packages/fable.core/1.2.4/fable-core/Option' in 'D:\WLCR\github\SAFE-BookStore\src\Client'
 @ ./App.fs 12:0-98
 @ ./Client.fsproj

ERROR in ./Utils.fs
Module not found: Error: Can't resolve 'C:/Users/kirichenko/.nuget/packages/fable.core/1.2.4/fable-core/Option' in 'D:\WLCR\github\SAFE-BookStore\src\Client'
 @ ./Utils.fs 2:0-100
 @ ./App.fs
 @ ./Client.fsproj

ERROR in ./pages/Login.fs
Module not found: Error: Can't resolve 'C:/Users/kirichenko/.nuget/packages/fable.core/1.2.4/fable-core/Option' in 'D:\WLCR\github\SAFE-BookStore\src\Client\pages'
 @ ./pages/Login.fs 15:0-98
 @ ./App.fs
 @ ./Client.fsproj

ERROR in ./pages/WishList.fs
Module not found: Error: Can't resolve 'C:/Users/kirichenko/.nuget/packages/fable.core/1.2.4/fable-core/Option' in 'D:\WLCR\github\SAFE-BookStore\src\Client\pages'
 @ ./pages/WishList.fs 18:0-110
 @ ./App.fs
 @ ./Client.fsproj
Running build failed.
Error:
System.Exception: dotnet fable webpack -- -p failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args) in D:\WLCR\github\SAFE-BookStore\build.fsx:line 79
   at FSI_0005.Build.clo@154-9.Invoke(Unit _arg7) in D:\WLCR\github\SAFE-BookStore\build.fsx:line 155
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target              Duration
------              --------
Clean               00:00:00.0206735
InstallDotNetCore   00:00:00.0746721
InstallClient       00:00:14.4629907
SetReleaseNotes     00:00:00.0021216
BuildServer         00:00:07.5078958
BuildClient         Failure
Total:              00:00:37.2132129
---------------------------------------------------------------------
Status:             Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: dotnet fable webpack -- -p failed
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at FSI_0005.Build.runDotnet(String workingDir, String args) in D:\WLCR\github\SAFE-BookStore\build.fsx:line 79
   at FSI_0005.Build.clo@154-9.Invoke(Unit _arg7) in D:\WLCR\github\SAFE-BookStore\build.fsx:line 155
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------

**Comment by forki** [comment]
cc @MangelMaxime @enricosada @alfonsogarciacaro ideas?

**Comment by MangelMaxime** [comment]
This path seems strange: `C:\Users\kirichenko.nuget\packages\fable.elmish.browser\1.0.0\fable`

I don't know if this is the copy/paste doing that but it's missing a `\` before `.nuget`

Can you try to install the project in the `C` drive ?

I am guessing from this line, that you are using `D` drive for the project. But the `.nuget` folder is on the `C` drive.

> Module not found: Error: Can't resolve 'C:/Users/kirichenko/.nuget/packages/fable.core/1.2.4/fable-core/Option' in 'D:\WLCR\github\SAFE-BookStore\src\Client\pages'

**Comment by MangelMaxime** [comment]
Also, can you tell us a little more about your env ? 
Version of dotnet.
Do you use, a fresh clone from this repo or upated the dependencies etc. ? :)

**Comment by irium** [comment]
I can confirm that on fresh clone the issue is reproducible.
But after `yarn upgrade fable-loader@1.1.4` and `paket update` the repo is at least builds.

So I guess it just repo using outdated versions of Fable libs.

**Comment by cartermp** [comment]
I can repro this today with the [2.1.3 Preview CLI/SDK drop](https://dotnetcli.blob.core.windows.net/licavalc/Sdk/2.1.3-preview3-fnl-007228/dotnet-sdk-2.1.3-win-x64.exe) and the latest master of this repository.

**Comment by forki** [comment]
But things were fixed!?

Am 30.11.2017 19:04 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by cartermp** [comment]
So this works if I use 2.1.1-preview-007094 (a build which has been on my machine since early November).

CLI/SDK 2.1.1-preview-007094 carries runtime version 2.0.3.
CLI SDK 2.1.3 carries runtime version 2.0.4.

I think the issue @vasily-kirichenko saw is fixed.  My observed failure is still from `dotnet fable webpack`, but it's MSBuild failing when invoked from the project cracker.

**Comment by enricosada** [comment]
> My observed failure is still from dotnet fable webpack, but it's MSBuild failing when invoked from the project cracker

@cartermp interesting. Can you open an issue in https://github.com/enricosada/dotnet-proj-info/issues about it?

**Comment by cartermp** [comment]
Yep, will do.
