### ISSUE TITLE
RFC: Add ConfPlanner to SAFE-Stack

### ISSUE THREAD

**Issue by rommsen** [SAFE-Stack/SAFE-BookStore#258]
Hi there,

I am not sure where to put this, so I leave this here. For a conference talk I built a small sample app showcasing the beauty of CQRS/Event-Sourcing in combination with Fable/Elmish. During the conference I talked to @isaacabraham and later to @forki  and they were interested in making the application a official demo application of the SAFE Stack. Here is the repo: https://github.com/rommsen/ConfPlanner

I think the application shows a couple of interesting things the bookstore app is not showing:

* reuse the complete domain model on the client and server
* Websockets with Elmish/Suave
* shows the nice fit of and similarity between CQRS/Event-Sourcing on the backend and the Elm-Architecture on the frontend
* reuse projections from the backend in the update function of the elmish app. The backend is sending the domain events to the frontend and the model is updated with the help of projections defined in the backend (on all clients that are connected via websockets).
* shows an easy way of implementing "Whatif"-Scenarios, i.e. scenarios that enable the user try out different actions. When the user is happy with the result the system sends a batch of commands to the server. When "Whatif-Mode" is enabled the client reuses not only the projections but also the domain behaviour defined on the server to create the events needed by the update function. The potential commands are also stored.
* using Fulma for styling

There are still a couple of things missing. We are planning to implement them in the future but any help would be appreciated
* Role based user management (planned for january)
* authentication via Websockets/JWT (planned for january)
* deployment to Azure
* having a live demo
* using a different Event Store than plain text files (maybe Cosmos DB or https://eventstore.org/)
* ... many ideas available but the system should not be too complex in the end

I would be more than happy, if there would still be interest in integrating the app into the SAFE-Stack.
I guess a lot needs to be done to accomplish this but I would be interested in your opinions first.

Regards,

Roman

**Comment by forki** [comment]
I would be very very happy if we could move it in the safe stack. Isaac can
give you admin rights and then you would still be in charge of the whole
thing.

Am 19.12.2017 08:34 schrieb "Roman Sachse" <notifications@github.com>:

**Comment by rommsen** [comment]
Really nice! I also will try to add more documentation.

// cc @heimeshoff

**Comment by isaacabraham** [comment]
@forki @rommsen done :-)

**Comment by rommsen** [comment]
Wow, I didn`t expect this to be done that fast :D I need to prepare a couple of things during the holidays and then I will transfer the repo.

**Comment by rommsen** [comment]
Thanks guys. All done.
