### ISSUE TITLE
show how to add external JavaScript to solution

### ISSUE THREAD

**Issue by ghost** [SAFE-Stack/SAFE-BookStore#268]
Hello,

First of all, I'm really impressed with the SAFE Stack and I kind of fell in love with it, so keep up the stuff you are doing!  This one has the potential to make F# finally big! 👍 

Your slogan should become: **Better SAFE than sorry** 

The only piece I am missing so far is documentation on how to add a JavaScript library or snippet to the solution in an idiomatic way, so that one can start doing the stuff described in [this](https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f) article right away.

**Comment by isaacabraham** [comment]
We need to sort the documentation out on the SAFE site - even a holding page that can take PRs for different areas would be good.

@Krzysztof-Cieslak I know you're busy - but is there a chance that over the next week or two you could put some kind of base for others to add docs to the site? Like a menu item + TOC (even if there's just one item in there) - from there others could add documentation, there could be issues for different areas etc.?
