### ISSUE TITLE
show how to add scss to solution

### ISSUE THREAD

**Issue by ghost** [SAFE-Stack/SAFE-BookStore#269]
It is me again. It would also be nice to have some guidance on how to configure that webpack.config.js thing so that you can compile css from scss (I am using Bulma and that would be a great thing for re-theming ... of basically any css framework)

**Comment by forki** [comment]
/cc @maxime_mangel

Am 19.01.2018 06:26 schrieb "Kai Friedrich" <notifications@github.com>:

**Comment by kfrie** [comment]
I played around a bit more with several more frameworks, one of them was [Semantic UI](https://semantic-ui.com/).

I found this [great article on Medium](https://medium.com/webmonkeys/webpack-2-semantic-ui-theming-a216ddf60daf) that got me on-boarded with this kind of stuff.

Would send PR with config and documentation, as soon as I am told which CSS framework is desired.
