### ISSUE TITLE
highlight usage of time-travelling debugger with Redux

### ISSUE THREAD

**Issue by ghost** [SAFE-Stack/SAFE-BookStore#273]
I took a deeper dive into the tool options that can be used with the SAFE stack and the BookStore sample.  The documentation part should stress a bit more the great experience that comes in combination with time-travelling debugger and react dev tools and how they play well together. Maybe one of those nice video gifs? Btw, what tool are you all using to create them?

An old pal from university visited me earlier and I demonstrated this to him ... regular programmers working with regular mainstream stuff will think you are an actual wizard or something 🤣 

I'm stressing this because it is one of the feature that really gets people hooked and if a friend who knows about Elm had not shown me [this video](https://youtu.be/zybahE0aQqA) I probably would not have been fiddling around with it too long. I only did because I wanted to have it really hard.

BTW, I'd love to help with this documentation stuff, as long as someone can tell me how to do this best.

**Comment by forki** [comment]
sure. we would love to see PR which shows this more

**Comment by kfrie** [comment]
@forki : I would like to do one of those gif vids. What program do you all use to make them. Would embed as a section in `README.md` and send PR

**Comment by Zaid-Ajaj** [comment]
@kfrie If you are on windows, I used to work with [Screen to gif](http://www.screentogif.com/downloads.html) where you record your screen and convert it to gif, it's extremely simple and generated high quality gifs (60FPS) I really loved working with it.

On linux, I am using [SimpleScreenRecorder](http://www.maartenbaert.be/simplescreenrecorder/) which is, well, very simple to work with, but you have to convert the generated video to gif yourself using some other program

**Comment by kfrie** [comment]
@Zaid-Ajaj Great, thank you, I like the Windows tool very much, useful for sort of things like bug reports. I will try to do a nice showcase for the time travel debugging feature.
