### ISSUE TITLE
Failure on first-time build

### ISSUE THREAD

**Issue by dsyme** [SAFE-Stack/SAFE-BookStore#278]
Steps

- Fork  + clone master a669d99a279c1be112c4e4f9d2f230fd9c7e36c1
- .\build.cmd

Got this:

![image](https://user-images.githubusercontent.com/7204669/35390819-98d62be6-01d4-11e8-81d6-4be9cd1151aa.png)

**Comment by kfrie** [comment]
seems like the UI Tests fail since some UI elements have been changed, but the tests have not been  updated. As a workaround you can simply comment them out in `build.fsx` to get it working:

```fsharp
Target "Build" DoNothing
Target "All" DoNothing

"Clean"
  ==> "InstallDotNetCore"
  ==> "InstallClient"
  ==> "SetReleaseNotes"
  ==> "BuildServer"
  ==> "BuildClient"
  ==> "BuildServerTests"
  ==> "RunServerTests"
  // ==> "BuildClientTests"
  // ==> "RenameDrivers"
  // ==> "RunClientTests"
  ==> "BundleClient"
  ==> "All"
  ==> "CreateDockerImage"
  ==> "TestDockerImage"
  ==> "PrepareRelease"
  ==> "Deploy"
```

**Comment by kfrie** [comment]
I investigated and the UI elements are in sync with the tests. I think something got messed up with user state on the client side. Probably the page gets rendered empty like in #274

**Comment by dsyme** [comment]
BTW switched to do ``build run`` and everything was ok from the first-time user perspective.  I hadn't seen the need for ``run`

**Comment by forki** [comment]
The "build run" is what starts everything in watch mode or what I like to
call "all the time Mode".

Am 25.01.2018 20:07 schrieb "Don Syme" <notifications@github.com>:

**Comment by kfrie** [comment]
yeah and it is an incredible development experience. 

I am also impressed with the deployment and release stuff you get out of the box (this is really important for adoption of commercial use I think). 
Release + Tag on GitHub, push to Docker Registry and deployment to Google Cloud an Azure with 2 commands once everything is set up. Awesome!
