### ISSUE TITLE
Old chromedriver fails against current chrome.exe

### ISSUE THREAD

**Issue by bohdanszymanik** [SAFE-Stack/SAFE-BookStore#288]
### Description

Using the 'start chrome' option on a current clone of the repository fails on my workstation due to the included chrome driver (2.27) being incompatible with current chrome (64). Quick fix is to download latest chromedriver (2.35).

### Repro steps

Please provide the steps required to reproduce the problem

1. git clone https://github.com/SAFE-Stack/SAFE-BookStore

2. comment out start phantomJS and replace with 'start chrome' in test\UITests\Runner.fs

3. build.cmd

### Expected behavior

UI automated tests in chrome

### Actual behavior

Chrome fails with 'cannot get automation extension'

### Known workarounds

Simply update chromedriver to match chrome version (listed in the section below) on workstation.

### Related information 

* Win 10
* .NET Core 2.1.3, .NET Framework 4.6.2
* Chrome 64.0.3282.140 (Official Build) (64-bit)
* chromedriver.exe 2.35 works, but version in repo 2.27 does not.

**Comment by forki** [comment]
I think this is outdated
