### ISSUE TITLE
Fable does not recognize port command during the build script

### ISSUE THREAD

**Issue by psfinaki** [SAFE-Stack/SAFE-BookStore#301]
(irrelevant: pffff, 3rd day in a row I am trying to do at least anything with the whole SAFE stack...)

When I run the build script, things go well until this line:
`dotnet fable --port free webpack-dev-server`
For this I get:
`Unrecognized command: --port. Use dotnet fable --help to see available options.`

App runs well at my 8080 if I remove `--port free` from this line in _build.fsx_:
`let fablewatch = async { runDotnet clientPath "fable --port free webpack-dev-server" }`

I am just starting with SAFE, have a little idea how things work here. ASAIU, fable actually _does_ support port option. Also I see [something](https://github.com/SAFE-Stack/SAFE-BookStore/pull/289) has been done around this recently. Maybe fable here is not updated to a version when it started to support this option?

**Comment by forki** [comment]
/cc @alfonsogcnunez

Am 25.02.2018 15:00 schrieb "Peter Semkin" <notifications@github.com>:

**Comment by MangelMaxime** [comment]
I think the args order is wrong.

It should be `webpack-dev-server --port free`.

```shell
> dotnet fable --help
Fable F# to JS compiler (1.3.17)
Usage: dotnet fable [command] [script] [fable arguments] [-- [script arguments]]

Commands:
  -h|--help           Show help
  --version           Print version
  start               Start Fable daemon
  npm-run             Run Fable while an npm script is running
  yarn-run            Run Fable while a yarn script is running
  node-run            Run Fable while a node script is running
  shell-run           Run Fable while a shell script is running
  webpack             Start Fable daemon, invoke Webpack and shut it down
  webpack-dev-server  Run Fable while Webpack development server is running

Fable arguments:
  --timeout           Stop the daemon if timeout (ms) is reached
  --port              Port number (default 61225) or "free" to choose a free port
  --verbose           Print more info during execution

To pass arguments to the script, write them after `--`. Example:

    dotnet fable npm-run build --port free -- -p --config webpack.production.js

You can use shortcuts for npm and yarn scripts in the following way:

    dotnet fable yarn-start       # Same as `dotnet fable yarn-run start`
```

**Comment by forki** [comment]
Please send PR. Also I assume the template might be wrong then. /cc
@theimowski

Maxime Mangel <notifications@github.com> schrieb am Fr., 13. Juli 2018,
09:48:

**Comment by theimowski** [comment]
Currently template doesn't use `--port free`. It should probably though
