### ISSUE TITLE
Paket.exe returns (503) Server Unavailable

### ISSUE THREAD

**Issue by skolkerom** [SAFE-Stack/SAFE-BookStore#302]
### Description

There is problem with updated paket.exe.

### Repro steps

1. Get the latest sources
2. Call paket.exe

### Expected behavior

No errors

### Actual behavior

The remote server returned an error: (503) Server Unavailable. (Github - cached (temporarily ignore updates))

### Related information 

* Windows 7 Professional
* .NET Core SDK version 2.1.3

**Comment by forki** [comment]
this should be fixed.

please delete paket.exe from `AppData\Local\NuGet\Cache\Paket`

**Comment by skolkerom** [comment]
I did that, but no success, unfortunately:

**`D:\Programming\SafeBookStore>dotnet nuget locals --clear all`
`info : Clearing NuGet HTTP cache: C:\Users\rvishnyakov\AppData\Local\NuGet\v3-cache`
`info : Clearing NuGet global packages cache: C:\Users\rvishnyakov\.nuget\packages\`
`info : Clearing NuGet Temp cache: C:\Users\rvishnyakov\AppData\Local\Temp\NuGetScratch`
`info : Local resources cleared.`**

**`D:\Programming\SafeBookStore>.paket\paket.exe`
`The remote server returned an error: (503) Server Unavailable. (Github - cached (temporarily ignore updates))`**

In addition, I run paket.exe itself, so my guess that nuget cache is not used in that case.

**Comment by forki** [comment]
weird /cc @vbfox

**Comment by skolkerom** [comment]
Some news.

If I try to run original bootstrapper file(named 'paket.exe'), then I get error 503 as described above.

But if I rename paket bootstrapper file to 'paket1.exe' and run it, then paket bootstrapper download paket.exe into the same directory where paket1.exe located (.paket directory).  After that I can build the project usual way by running build.cmd.

Maybe the cause of that problem is the same names of the paket.exe itself and paket bootstrapper?

**Comment by vbfox** [comment]
@forki Sorry but I don't have any idea. I tried on a machine that never had paket installed to checkout the repo and didn't saw any problem

<details>

```
Using strategy: Github - cached (temporarily ignore updates)
Checking Paket version (downloading latest stable)...
Target path is C:\Users\jroncagl\AppData\Local\Temp\paket_D95549D0EC6D7581953C8239640F3B0EDE7A7AA5D4BE97AF4FFBD228D048CB81.exe
File doesn't exists, no version information: C:\Users\jroncagl\AppData\Local\Temp\paket_D95549D0EC6D7581953C8239640F3B0EDE7A7AA5D4BE97AF4FFBD228D048CB81.exe
File in target path version: vUNKNOWN
No version specified, checking online...
[Github - cached (temporarily ignore updates)] GetLatestVersion...
File doesn't exists, no version information: C:\Users\jroncagl\AppData\Local\Temp\paket_D95549D0EC6D7581953C8239640F3B0EDE7A7AA5D4BE97AF4FFBD228D048CB81.exe
Target file last modification: 1/1/1601 1:00:00 AM
Target file is older than 720 minutes or not found.
[Github - cached] GetLatestVersion...
[Github] GetLatestVersion...
[Github] GetLatestVersion took 0.99 second(s) and returned '5.142.0'.
[Github - cached] GetLatestVersion took 0.99 second(s) and returned '5.142.0'.
[Github - cached (temporarily ignore updates)] GetLatestVersion took 1 second(s) and returned '5.142.0'.
Latest version check found v5.142.0 in 1 second(s)
Downloading hash for v5.142.0 ...
[Github - cached (temporarily ignore updates)] DownloadHashFile...
[Github - cached] DownloadHashFile...
Hash file of version 5.142.0 not found in cache.
[Github] DownloadHashFile...
Starting download from https://github.com/fsprojects/Paket/releases/download/5.142.0/paket-sha256.txt
[Github] DownloadHashFile took 0.62 second(s) and returned '1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D paket.exe'.
Writing hashFile file in cache.
hashFile -> C:\Users\jroncagl\AppData\Local\NuGet\Cache\Paket\5.142.0\paket-sha256.txt
[Github - cached] DownloadHashFile took 0.63 second(s) and returned '1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D paket.exe'.
[Github - cached (temporarily ignore updates)] DownloadHashFile took 0.63 second(s) and returned '1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D paket.exe'.
Hash download took 0.63 second(s)
Downloading v5.142.0 ...
[Github - cached (temporarily ignore updates)] DownloadVersion...
[Github - cached] DownloadVersion...
Version 5.142.0 not found in cache.
[Github] DownloadVersion...
Starting download from https://github.com/fsprojects/Paket/releases/download/5.142.0/paket.exe
Expected hash  = 1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D
paket.exe hash = 1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D (C:\Users\jroncagl\AppData\Local\Temp\paket4064)
Hash of downloaded file successfully found in 1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D paket.exe
[Github] DownloadVersion took 4.6 second(s) and returned 'void'.
Expected hash  = 1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D
paket.exe hash = 1CF30B28F564420C324DF317FED062CEF972DD0C63EC8D07D5E7CD0E3252F54D (C:\Users\jroncagl\AppData\Local\Temp\9bae1625-0875-45c3-92e5-4d72c037d165)
Caching version 5.142.0 for later, hash is ok
[Github - cached] DownloadVersion took 5.4 second(s) and returned 'void'.
[Github - cached (temporarily ignore updates)] DownloadVersion took 5.98 second(s) and returned 'void'.
Download took 5.98 second(s)
Done in 7.65 second(s).
Paket Bootstrapping took 7.65 second(s)
```
</details>

Magic mode is affecting the filesystem part of paket but not the downloading part that happens as before so there shouldn't be any differences there

**Comment by skolkerom** [comment]
Ok, I'll try to reproduce this error on another computer few hours later.

**Comment by skolkerom** [comment]
There is error only on my work machine. I can't repro issue on my home notebook.

**Comment by realvictorprm** [comment]
@skolkerom are you using any proxy?

**Comment by skolkerom** [comment]
@realvictorprm Yes, my work machine is behind corporate proxy.

**Comment by realvictorprm** [comment]
This could be a problem but I don't know details, @forki got maybe a clue.

**Comment by NullVoxPopuli** [comment]
I have this issue on master

**Comment by codehutch** [comment]
I had this issue on LInux today with clean checkout of latest version:

```Error: SendFailure (Error writing headers) (Github - cached (temporarily ignore updates))```

Workaround is: 
```
mv .paket/paket.exe .paket/paket.bootstrapper.exe
.paket/paket.bootstrapper.exe
```
Then build as usual:
- ```./build.sh run```

**Comment by drk-mtr** [comment]
I was having a similar issue when trying to build a project that works fine on one PC on another PC. 

`The remote server returned an error : (404) Not Found. (Github - cached)`

It would be really helpful if it could tell us what resource it's trying to request at this point, but I'm not sure whether this is paket or dotnet that's reporting this failure.

For me, the fix was to comment the version number out of `paket.dependencies` and deleting all `paket.exe` files from `AppData\Local\NuGet\Cache\Paket`. (I know, I really need to get out of the habit of applying two "fixes" at once so I can pinpoint these things better!)
