### ISSUE TITLE
Release script does not work for Windows containers

### ISSUE THREAD

**Issue by psfinaki** [SAFE-Stack/SAFE-BookStore#307]
### Repro steps

1. Install Docker, set up Windows containers
2. Follow deployment [instructions](https://github.com/SAFE-Stack/SAFE-BookStore#deployment), run `release.cmd`

### Expected behavior

Code gets published to Docker hub

### Actual behavior

```
docker: Error response from daemon: failed to create endpoint test on network nat: Windows does not support host IP addresses in NAT settings.
Running build failed.
Error:
System.Exception: Docker run failed
   at FSI_0005.Build.clo@290-21.Invoke(Unit _arg7) in <my project location>\build.fsx:line 298
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
```

### Known workarounds

Switch to Linux containers.

### Related info

I am running this on Windows 10 x64.

### Ideas

I do not know if it is expected behavior. If it is, then it is worth mentioning in docs.

**Comment by forki** [comment]
not supported - not fault of SAFE stack

**Comment by forki** [comment]
I wrote a comment into the docs. thanks
