### ISSUE TITLE
Dockerization of the app does not work on port 8085

### ISSUE THREAD

**Issue by psfinaki** [SAFE-Stack/SAFE-BookStore#308]
### Repro steps

1. Install Docker, set up Linux containers
2. Follow deployment instructions, run `release.cmd`

### Expected behavior

Code gets published to Docker hub.

### Actual behavior

docker: Error response from daemon: driver failed programming external connectivity on endpoint test (e627eb4c8999a1aace70407d7619d88700a06e051cc1934ec8106b05951b18bc): Error starting userland proxy: Bind for 127.0.0.1:8085 failed: port is already allocated.
Running build failed.
Error:
System.Exception: Docker run failed
   at FSI_0005.Build.clo@290-21.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

### Known workarounds

Open `build.fsx`, and change 8085 to 8086 in this magical line of code:
`info.Arguments <- sprintf "run -d -p 127.0.0.1:8085:8085 --rm --name %s -it %s/%s" testImageName dockerUser dockerImageName) TimeSpan.MaxValue`

I do not know exactly why this works however I believe it may be connected to the fact that some Giraffe is running on port 8085.

### Related info

I am running this on Windows 10 x64.

**Comment by forki** [comment]
this sounds as you have already something running on that port

**Comment by psfinaki** [comment]
@forki,

I have now tried the same thing gazing at Resource Monitor.

In the beginning nothing runs on 8085. 
Then at the point when the log says `Now listening on: http://localhost:8085`, Resource Manager inserts _dotnet_ at port 8085 (pretty logical, yep).

And then it stays there. After the release script fails, that line gets grayed out. In some time it disappears.

**Comment by forki** [comment]
weird.

![image](https://user-images.githubusercontent.com/57396/37053977-e9a8a2ec-217d-11e8-9040-5f24b68482f5.png)

this line should actually kill the giraffe process after testing is done.

**Comment by forki** [comment]
or I can actually repro. Fixing it now!
Thanks for reporting

**Comment by forki** [comment]
ok fixed. thanks

**Comment by psfinaki** [comment]
Yep, working now. Thanks for quick fix!
