### ISSUE TITLE
Service Unavailable when starting Azure Web App

### ISSUE THREAD

**Issue by psfinaki** [SAFE-Stack/SAFE-BookStore#310]
Yes, this is what I saw after following README tutorial.

I read [this](https://blogs.msdn.microsoft.com/waws/2017/09/08/things-you-should-know-web-apps-and-linux/), opened Kudu, downloaded Docker logs, this is what I see there, enjoy:

```
2018-03-06 12:21:00.325 INFO  - Starting container for site
2018-03-06 12:21:00.325 INFO  - docker run -d -p 39943:8085 --name <my app>_1 -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITES_PORT=8085 -e WEBSITE_SITE_NAME=<my app> -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_INSTANCE_ID=6461b2031bd7f08beea38b4037ff8691b9084daa6e55aa934faa2ce233726a33 -e HTTP_LOGGING_ENABLED=1 <my_image>

2018-03-06 12:31:02.809 INFO  - Container logs
2018-03-06T12:21:03.206693125Z Hosting environment: Production
2018-03-06T12:21:03.206922923Z Content root path: /client
2018-03-06T12:21:03.207647617Z Now listening on: http://localhost:8085
2018-03-06T12:21:03.207779316Z Application started. Press Ctrl+C to shut down.

2018-03-06 12:31:02.810 ERROR - Container <my app>_1 for site <my app> did not start within expected time limit. Elapsed time = 600.7570032 sec
2018-03-06 12:31:03.933 INFO  - Issuing docker pull: imagename =<my image>
2018-03-06 12:31:05.444 INFO  - Issuing docker pull: imagename =<my image>
2018-03-06 12:31:06.667 INFO  - Issuing docker pull <my image>
2018-03-06 12:31:08.297 INFO  - docker pull returned STDOUT>> latest: Pulling from <my image>
Digest: sha256:2f9cb2d17167fa00417a27cf6e152b8cd2fec7439d15811b76df1cb3ec49cf0f
Status: Image is up to date for <my image>
```

**Comment by psfinaki** [comment]
Guys, I am tired. I think I give up. I have been trying to bring this whole thing to work for a week. Docker does not run on my machine (I have Windows x86), I have to run release scripts either from work or from virtual machines. And it constantly brings issues ([1](https://github.com/SAFE-Stack/SAFE-BookStore/issues/307), [2](https://github.com/SAFE-Stack/SAFE-BookStore/issues/308)). And Web App for containers costs 50 EUR a month in Azure (whereas pure web services cost nothing). And it still does not work.

I understand that docker is cool but I do not know it much and do not want to dive into it now. I want to write my application in my F#, not studying the hell of docker bugs. I am very disappointed by all this stuff.

**Comment by forki** [comment]
you don't need docker for this!? It's just one option to do it

**Comment by forki** [comment]
btw: according to the log everything is set up correctly in the docker. so something on your azure portal is setup wrongly. Did you set the port properly in the config?

**Comment by WalternativE** [comment]
Sorry to hear about your experience. Pure Azure Web Apps don't cost anything, that is true. As @forki correctly stated the Docker deployment is merely one of many options in this example. Depending on your backend (giraffe/suave) you can adjust the deployment according to your needs. This application (https://github.com/WalternativE/fableshotdetection) - to give you an example - uses a Suave server side component which is deployed to Azue Web Apps (the needed config for this is in the web.config in the src/Server directory).

**Comment by psfinaki** [comment]
@forki Yes, I have set up the port. By the way, AFAIU, one does not have to do it via Azure Shell anymore, app settings should be enough.
![settings](https://user-images.githubusercontent.com/5451366/37038624-965c2668-2155-11e8-977b-ba18e3a89dc8.png)

**Comment by forki** [comment]
Isn't it called PORT instead of WEBSITES_PORT!?

**Comment by isaacabraham** [comment]
@psfinaki sorry to hear you've been running into problems. I'd be happy to help you sort this out to run on the standard app service if you'd like - drop me a message privately and we can sort it out.

**Comment by psfinaki** [comment]
@forki, this is how it is in the [README](https://github.com/SAFE-Stack/SAFE-BookStore#azure-portal).
But PORT does not help. I also tried WEBSITE_PORT, to no avail.

**Comment by forki** [comment]
Well according to the logs the docker is running fine and is not to blame
here.

Am 06.03.2018 17:56 schrieb "Peter Semkin" <notifications@github.com>:

**Comment by psfinaki** [comment]
@WalternativE,
Thank you for your support :)

Like... Imagine, I have never touched Suave, Giraffe, Fable, Elm. I have done some web app with service in F# and client in jQuery + AJAX. Now I want to get more profound, and for me all this stack apart from Azure is total magic.

Thus I just wanted to get things up and running and then start cautiously adjusting and changing things. I had no idea it can somehow run without docker as current docs offer docker deployment without alternatives, not even mentioning them

**Comment by psfinaki** [comment]
@isaacabraham,
Thanks for your wish to help. Quick test of deployment the Github code to the app service did not work so I will likely write you soon on that.

**Comment by forki** [comment]
@psfinaki well this is an opionated sample project. Not some official docs on doing safe. In this project I chose docker for deployment because I seriously believe it's the best option for deployment. By far.
Tbf we did a poor job here to tell about alternatives, which are magic as well (just for another group of people). 

We have other safe stack samples here that don't use docker and AFAIK we have a dotnet template that allows you to opt out.
So I apologize if it made it look as it's the only option. It is one option and for me personally the best. Nothing more

**Comment by psfinaki** [comment]
This is not an official docs, however:
1) It is the pinned repo in SAFE-stack
2) SAFE-template refers to here for deployment
3) Other repos in SAFE-stack do not seem to have any info about deployment
4) Current doc looks extensive and serious so one expects it to be like this in every aspect

@forki,
I am not trying to blame you, rather just sharing the experience of a newcomer here. Maybe it is not the best place, hehe

**Comment by isaacabraham** [comment]
@psfinaki The house price sample has an alternative deployment mechanism that we are documenting but yes we need to put some docs on the site about the azure story

**Comment by forki** [comment]
@psfinaki yes I do understand that and I'm seriously trying to make it as good as possible for newcomers while still keeping it a real world thing with what I think is working well in real world scenarios. I don't think you know how much time myself and others put into this.

**Comment by forki** [comment]
Ok let's go forward from here: is it possible to open a support ticket for azure? The docker container is clearly running. Docker is one of the recommended ways to deploy asp.net core apps. We don't really do anything special here - it's the same as C# people do. I personally assume there is something wrong with port mapping. I will try to do deployment later today to verify that it's still working.

**Comment by forki** [comment]
ok I can repro. and I think I know what's going on.
brb

**Comment by forki** [comment]
seems I was wrong about my idea. needs to investigate tomorrow. 
will come back to you. Thanks for reporting - I can see how this is frustrating.

**Comment by forki** [comment]
looks like it's completely unrelated to all this here:

    2018-03-07T07:39:35.513984666Z Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'WishListWebJobs.ClearWishListsWebJob' ---> System.InvalidOperationException : Cannot bind parameter '$return' to type Unit&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).

@isaacabraham ever seen that before?

**Comment by forki** [comment]
ok I disabled the webjob for now. app runs fine now: https://fable-suave.azurewebsites.net/#home

so in other words: @psfinaki your deployment worked fine - it was something that changed around webjobs and which broke from bookstore v.0.8 (that container still works fine) to today.

**Comment by psfinaki** [comment]
@forki, hurrrraaahh, I have finally managed to deploy the app to Azure! 
Actually, for me things seems to work without port mapping, maybe again due to some internal changes.

**Comment by forki** [comment]
Well it was properly deployed before. It was just that the code inside the container itself regressed and we don't have a test for that part yet

**Comment by psfinaki** [comment]
@isaacabraham, 
I will look into that app then, thank you for the tip. 
I have at least something working and now I can finally start hacking, breaking and trying things.

**Comment by psfinaki** [comment]
@forki, yep, I understand now. Maybe then this issue should be closed now.

**Comment by andrismudiayi** [comment]
im using azure webapp with docker-compose, i have 2 basic containers, an asp.net website with a swagger endpoint, and a redis container..the logs show they startup fine, but when i browse to it it takes ages until it fails..i look at the logs no errors..its been 3days and it fails even with most basic configs..any ideas how to resolve this?
