### ISSUE TITLE
Passing parameters to webpack and webpack-dev-server

### ISSUE THREAD

**Issue by cgravill** [SAFE-Stack/SAFE-BookStore#313]
### Description

With the switch to Webpack 4.x there's a warning I wanted to address:

```
WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.
```

I've done this in other projects by adjusting the packages.json scripts to pass in `--mode development` then invoke the webpack server via `dotnet fable yarn-start`

In this sample, because it uses the commands `fable webpack` or fable `webpack-dev-server` they're explicitly matched:

https://github.com/fable-compiler/Fable/blob/ca91c7962edbcff964132d138954ce27c2ce7cc0/src/dotnet/dotnet-fable/Main.fs#L255

and most additional arguments are dropped (the port argument is explicitly read and passed).

### Repro steps

run `build run` and wait for the warning

### Expected behavior

Be able to configure webpack via build.fsx.

### Actual behavior

Parameters are dropped

### Possible fixes

Either Fable could be changed to also pass additional arguments or the store could more directly invoke webpack.

### Related information 

* Operating system: Windows 10
* Branch: master

**Comment by alfonsogarciacaro** [comment]
The arguments are passed to Fable CLI. You can redirect some to the subprocess by writing them after `--` as it's customary in other cli tools (like `npm run`).

```shell
dotnet fable yarn-start -- --mode development
```

> BTW, I think `dotnet fable webpack` doesn't work for Webpack 4, as they've changed the main file location. For now, it's better to call Webpack through a package.json script like `start` or `build`.

In any case, I'd recommend setting the Webpack 4 mode in the webpack.config.js file:

```js
module.exports = {
    mode: isProduction ? "production" : "development",
    ...
}
```

The way to pass arguments to the subprocess is also explained in the help text :)

```fsharp
~/d/C/s/Client ❯❯❯ dotnet fable -h
Fable F# to JS compiler (1.3.8)
Usage: dotnet fable [command] [script] [fable arguments] [-- [script arguments]]

Commands:
  -h|--help           Show help
  --version           Print version
  start               Start Fable daemon
  npm-run             Run Fable while an npm script is running
  yarn-run            Run Fable while a yarn script is running
  node-run            Run Fable while a node script is running
  shell-run           Run Fable while a shell script is running
  webpack             Start Fable daemon, invoke Webpack and shut it down
  webpack-dev-server  Run Fable while Webpack development server is running

Fable arguments:
  --timeout           Stop the daemon if timeout (ms) is reached
  --port              Port number (default 61225) or "free" to choose a free port
  --verbose           Print more info during execution

To pass arguments to the script, write them after `--`. Example:

    dotnet fable npm-run build --port free -- -p --config webpack.production.js

You can use shortcuts for npm and yarn scripts in the following way:

    dotnet fable yarn-start       # Same as `dotnet fable yarn-run start`
```

**Comment by cgravill** [comment]
I've put in a small change so the development mode runs that way. It seems to be working for both `run` and `BuildClient` on WebPack V4 for me.

**Comment by alfonsogarciacaro** [comment]
That's great, thank you! I've also played a bit with Webpack 4 and I'm trying to use the new defaults to reduce the code in webpack.config.js, but I'm planning to release with Fable 2. We can wait until that or you can PR the changes, whatever works best for you :)

**Comment by cgravill** [comment]
I was curious about the history on the extra `--` and located the original npm change: https://github.com/npm/npm/pull/5518 including lots of confused people! :)

**Comment by alfonsogarciacaro** [comment]
Yes, we had another discussion before releasing Fable 1 but I cannot find the issue right now. Before it was something like `--args "--mode developement"`, but one user suggested `--` to follow npm's approach. However now yarn has removed the need of `--` because it's indeed confusing :)

Maybe we could allow something like the following for Fable 2. What do you think?

```
dotnet fable --port free webpack --mode development
```

**Comment by cgravill** [comment]
I'll close this as it's working now and there's a separate issue for discussing command changes for Fable 2
