### ISSUE TITLE
paket.exe version causes build failure

### ISSUE THREAD

**Issue by fergusmeiklejohn** [SAFE-Stack/SAFE-BookStore#330]
### Description

Problem with paket.exe is preventing the build process from running
Related issues:
https://github.com/MangelMaxime/Fulma/issues/138
https://github.com/fsprojects/Paket/issues/3180

### Repro steps

1. Cloned project

2. `./build.sh run`

3. Loops with `paket.locked is locked by paket.exe (pid = 1472) Waiting...`

### Known workarounds

Problem solved by deleting paket.exe and replacing with latest stable version 5.156.7

### Related information 

OSX
Latest version of the repo

**Comment by forki** [comment]
Can you please retry with fresh clone?

Fergus Meiklejohn <notifications@github.com> schrieb am Do., 3. Mai 2018,
03:55:

**Comment by fergusmeiklejohn** [comment]
It builds fine now
