### ISSUE TITLE
Warning for Dotnet Core 2.1.300 SDK

### ISSUE THREAD

**Issue by kunjee17** [SAFE-Stack/SAFE-BookStore#334]
This is not actually an issue. But more of an enhancement. I am filling this issue for future reference. Feel free to close it if you don't find it appropriate. 

I just moved my project to `2.1.300` latest SDK. Everything works and works faster. But I am getting warning for watch tools

```
/usr/local/share/dotnet/sdk/2.1.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ObsoleteReferences.targets(33,5): warning : The tool 'Microsoft.DotNet.Watcher.Tools' is now included in the .NET Core SDK. Information on resolving this warning is available at (https://aka.ms/dotnetclitools-in-box). [/src/Server/Server.fsproj]
```

We are generally adding watch tools using paket. But I guess they have changed something so we need to update read me. Please have a look. 

Let me know if any further details are required.

**Comment by isaacabraham** [comment]
Watch is now built-in to .net sdk, so it can be removed from paket I believe.

**Comment by kunjee17** [comment]
@isaacabraham I ll have a look and update here.

**Comment by kunjee17** [comment]
Yup. Watch is working without adding watcher tool... We can update our read me for same. 

cc/ @isaacabraham @forki

**Comment by forki** [comment]
please send a pr that removes it

**Comment by kunjee17** [comment]
@forki  sure I ll do it by EOD (India Time)...
