### ISSUE TITLE
after logging in, firefox runs into an endless loop and allocates

### ISSUE THREAD

**Issue by 0x53A** [SAFE-Stack/SAFE-BookStore#344]
When I go to http://fable-suave.azurewebsites.net and log in in, my firefox hangs and endlessly allocates:

![image](https://user-images.githubusercontent.com/4236651/41688724-88611f6e-74ed-11e8-9293-d9da91ccfbb1.png)

Once it went up to 9GB until I finally killed it.

I can reproduce it reliably, can you try if it also happens for you?

This only happens directly after login - if I restart firefox, then the login-cookie is saved and I can use the wishlist as normal.

**Comment by forki** [comment]
Does it also happen on self-built? The deployed version is a bit outdated

Lukas Rieger <notifications@github.com> schrieb am Do., 21. Juni 2018,
00:55:
