### ISSUE TITLE
The demo web site is not working

### ISSUE THREAD

**Issue by psfinaki** [SAFE-Stack/SAFE-BookStore#354]
Hey guys, http://fable-suave.azurewebsites.net/ currently returns `ERR_NAME_NOT_RESOLVED`.

**Comment by forki** [comment]
Yes I had to take it down because my free credits were not enough. But
@isaac_abraham wants to host it now

Peter Semkin <notifications@github.com> schrieb am Di., 7. Aug. 2018, 01:33:

**Comment by psfinaki** [comment]
I see. Btw, how much does it cost monthly?

**Comment by forki** [comment]
Please reopen

Peter Semkin <notifications@github.com> schrieb am Di., 7. Aug. 2018, 09:30:

**Comment by psfinaki** [comment]
Oops, apologies, pressed the wrong button.

**Comment by klettier** [comment]
Hi,

Any update on this ? It's weird to have the first link of the page that is not working.
Maybe could you just remove it until it's back ?

kévin

**Comment by forki** [comment]
ok it's live again at https://safe-bookstore.azurewebsites.net/

**Comment by forki** [comment]
need to move it again.
