### ISSUE TITLE
Unusual project setup breaks language services in Ionide and VS for Mac

### ISSUE THREAD

**Issue by inosik** [SAFE-Stack/SAFE-BookStore#368]
### Description

@fergusmeiklejohn asked on Gitter why the language services don't work properly when following [the instructions](https://github.com/SAFE-Stack/SAFE-BookStore#create-a-new-page) to add a new page in the README. I noticed the unusual project setup, which looks something like this:

``` text
src/Client/Client.fsproj
  Imports src/Shared/Shared.props
    Imports src/Shared/Client.props
      Includes all F# files in src/Client/
```

I guess this is done to include the client files in the server for SSR. But this setup breaks language services in Ionide on Windows and in VS for Mac, as reported by @fergusmeiklejohn.

### Repro steps

Clone this repository and follow [the instructions](https://github.com/SAFE-Stack/SAFE-BookStore#create-a-new-page)  in the README using VS Code and Ionide. Add the new file to `Client.props`.

### Expected behavior

The new F# file is picked up by the language services and IntelliSense works.

### Actual behavior

IntelliSense doesn't work in the new file, and it doesn't show up in the solution explorer. You have to close and reopen your IDE.

### Known workarounds

Add the new file to `Client.fsproj` instead of `Client.props`.

### Related information 

* Operating system: Windows, macOS
* Branch: `master`

**Comment by forki** [comment]
//cc @Krzysztof-Cieslak
