### ISSUE TITLE
Paket failed with could not download FAKE 5.3 from https://www.nuget.org/api/v2/package/FAKE/5.3.0

### ISSUE THREAD

**Issue by YunWeiaa** [SAFE-Stack/SAFE-BookStore#370]
### Description
VS Enterprise 2017 d15.9stg: Version 15.9.0 Preview 4.0 [28217.54.d15.9]
Node.js: V8.12.0
Yarn --version:1.10.1
### Repro steps

Master branch of SAFE Bookstore
Install the needed deps for [SAFE-Bookstore](https://github.com/SAFE-Stack/SAFE-BookStore)
In the root directory, run build.cmd
Output:
![11](https://user-images.githubusercontent.com/33921754/47148745-1b879380-d304-11e8-9dae-d64af29f8c32.png)
Wait for a while, it shows **Message: Could not download FAKE 5.3 from https://www.nuget.org/api/v2/package/FAKE/5.3.0.**
![222](https://user-images.githubusercontent.com/33921754/47148815-57225d80-d304-11e8-8d87-8f5da682996f.png)
Then it shows **Paket failed with
-> Could not download FAKE 5.3 from https://www.nuget.org/api/v2/package/FAKE/5.3.0.
-> TaskCanceledException: A task was canceled.**
![333](https://user-images.githubusercontent.com/33921754/47148921-a8cae800-d304-11e8-9178-6406c3065a48.png)

### Expected behavior
Automatic download FAKE 5.3 well.

### Actual behavior

Could not download FAKE 5.3 from https://www.nuget.org/api/v2/package/FAKE/5.3.0.

### Related information 

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   <C:\Program Files\dotnet\sdk\2.1.403\>

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.1.11 [<C:\Program Files\dotnet\sdk>]
  2.1.403 [<C:\Program Files\dotnet\sdk>]
  2.1.500-preview-009335 [<C:\Program Files\dotnet\sdk>]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [<C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All>]
  Microsoft.AspNetCore.App 2.1.5 [<C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App>]
  Microsoft.NETCore.App 1.0.13 [<C:\Program Files\dotnet\shared\Microsoft.NETCore.App>]
  Microsoft.NETCore.App 1.1.10 [<C:\Program Files\dotnet\shared\Microsoft.NETCore.App>]
  Microsoft.NETCore.App 2.1.5 [<C:\Program Files\dotnet\shared\Microsoft.NETCore.App>]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download 
```

**Comment by forki** [comment]
can you access nuget.org at all?
