### ISSUE TITLE
http://localhost:8080/login doesn't work

### ISSUE THREAD

**Issue by forki** [SAFE-Stack/SAFE-BookStore#373]
@MangelMaxime @alfonsogarciacaro  I didn't notice before but something seems to be wrong with the webpack.config:

Repro:

* build.cmd run
* go to http://localhost:8080
* click "login" -> Login page works
* press F5 -> bääm

![image](https://user-images.githubusercontent.com/57396/48135990-cacddf80-e29e-11e8-964c-c67a0b2e58bc.png)

**Comment by MangelMaxime** [comment]
Are the other pages doing the same ?

I am pretty sure that I tested the SSR feature when converting to Fable 2.

**Comment by forki** [comment]
yes that's broken everywhere.

**Comment by forki** [comment]
And it's not even the SSR - this is going against the webpack dev server
which does not do SSR.

Am Mi., 7. Nov. 2018, 15:29 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by MangelMaxime** [comment]
Ah ok I guess I understand.

So the problem is that we are using not hased url and so it's trying to fetch the `login.html` file. Can you check if I removed a setting compare to the Fable 1 config in the webpack.config.js

I am asking because I am already working on your other bug :p

**Comment by forki** [comment]
Sure, will check. This was only to ask if it rings a bell.

Am Mi., 7. Nov. 2018, 15:59 hat Maxime Mangel <notifications@github.com>
geschrieben:

**Comment by forki** [comment]
did the fix work for you?

**Comment by MangelMaxime** [comment]
Yes the fix works for me.

![2018-11-08 08 57 51](https://user-images.githubusercontent.com/4760796/48185158-7aa15c80-e334-11e8-9b1f-ebd8686f4be8.gif)

**Comment by forki** [comment]
ok. thanks

I wonder why it doesn't work on my "big" project. need to dig deeper

Am Do., 8. Nov. 2018 um 08:58 Uhr schrieb Maxime Mangel <
notifications@github.com>:

**Comment by forki** [comment]
ok. copied your config from scratch. now it works. you are my hero. again.

![zelda](https://user-images.githubusercontent.com/57396/48251419-dd145e80-e401-11e8-8c92-6d271de1e1c1.gif)

**Comment by MangelMaxime** [comment]
@forki Perfect :)

**Comment by artem-hryb** [comment]
Hi, guys. There is another error with login flow:
To reproduce:
build.cmd RunSSR
go to http://localhost:8080/login
Enter test/test,
Click 'Log in'
Nothing happens

Dev. console output shows:
"Uncaught SyntaxError: Unexpected token <"

**Comment by MangelMaxime** [comment]
Hello @artem-hryb 

I can't repro your problem.

![2018-11-09 11 28 04](https://user-images.githubusercontent.com/4760796/48257381-ad218700-e412-11e8-95a9-acb36f5a1158.gif)

Are you using latest `master` branch ?

**Comment by artem-hryb** [comment]
@MangelMaxime I've just taken latest. It works well for me now. Thank you.
