### ISSUE TITLE
Debugging issue in Visual Studio Code

### ISSUE THREAD

**Issue by skolkerom** [SAFE-Stack/SAFE-BookStore#383]
### Description

Can't debug application in VS Code.

### Repro steps

Do steps from debugging section: https://github.com/SAFE-Stack/SAFE-BookStore#debugging

### Expected behavior

Successfully started debugging process

### Actual behavior

No started debugging process: browser not started, application on localhost:8080 is not accessible.

### Related information 

* Operating system: Windows 10
* Core CLR version: 
```
dotnet --version
2.2.100
```
* End of debugging console output:

```
Hosting environment: Production
Content root path: C:\Programming\SafeBookstore\src\Client
Now listening on: http://0.0.0.0:8085
Application started. Press Ctrl+C to shut down.
The thread 13564 has exited with code 0 (0x0).
```

That issue maybe related to https://github.com/SAFE-Stack/SAFE-BookStore/issues/332, but it doesn't contain any useful information.

P.S. This problem is reproduced on my both machines: desktop and laptop

**Comment by darde** [comment]
Ensure your `.vscode/launch.json` is setting the **Server.dll** with the correct path: In my case, I had to change the path from **netcoreapp2.0** to **netcoreapp2.2**.

`"program": "${workspaceRoot}/test/ServerTests/bin/Debug/netcoreapp2.2/Server.dll",`
