### ISSUE TITLE
Cannot find file specified

### ISSUE THREAD

**Issue by tombutlerjr** [SAFE-Stack/SAFE-BookStore#386]
### Description

fable-compiler 2.1.3
C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\src\Client> dotnet restore Client.fsproj
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Frameworks, Version=4.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified. [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: File name: 'NuGet.Frameworks, Version=4.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task, Stream stream) [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromMemory(ResolvePackageAssets task, Byte[] settingsHash) [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]
C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error MSB4018: [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj] [C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj]

  The build failed. Please fix the build errors and run again.
C:\Users\tombu\Desktop\F#\SAFE-BookStore-master\test\ServerTests\ServerTests.fsproj(18,5): error MSB3073: The command "C:\Users\tombu\AppData\Local\dotnetcore\dotnet.exe run" exited with code 1.
watch : Exited with error code 1

### Repro steps

running ./build.cmd run gives the above error.  At this point, the login opens, but cannot login
* Windows 10
* latest
* dotnet --version 2.2.105
* running on .net core, or building from command  prompt

**Comment by LauriListak** [comment]
Can confirm also the same happening on Windows 10 build 17763 and dotnet version 2.2.105.

Where is Nuget.Frameworks supposed to be located? Because it doesn't seem to be there in the project:

```
X@Y MINGW64 ~/Projects/SAFE-BookStore (master)
$ find . | grep NuGet
./NuGet.config
./packages/build/FAKE/tools/NuGet.Core.dll
./src/AzureFunctions/RecurringJobs/obj/RecurringJobs.fsproj.NuGet.Config
./src/Client/obj/Client.fsproj.NuGet.Config
./src/Server/obj/Server.fsproj.NuGet.Config
./test/ServerTests/obj/ServerTests.fsproj.NuGet.Config
./test/UITests/obj/UITests.fsproj.NuGet.Config
```

**Comment by BlooDCrescent** [comment]
Confirm this issue, cannot run the required build.cmd script on Windows 10 build 16299, dotnet -- version 2.2.103. The solution above miraculously works
